FROM node:22-slim

# Evita futuros errores instalando dependencias nativas que Three.js y Vite a veces necesitan
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml* ./
COPY pnpm-workspace.yaml* ./


# Instalamos de forma forzada ignorando bloqueos de versiones
RUN pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 5173

# El flag --host previene el error de "no puedo ver la web en mi navegador"
CMD ["pnpm", "run", "dev", "--host"]