/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [43.47KB] > F:\mongame-frontend\src\public\3d-meshes\neon_background\scene-transformed.glb [269.29KB] (-519%)
Author: ChristyHsu (https://sketchfab.com/ida61xq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scifi-tron-studio-baked-88c7b7b5adc54b2eab451ebaf55ce941
Title: Scifi Tron Studio | Baked
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import neonBgGlbUrl from '@/public/3d-meshes/neon_background/scene-transformed.glb'

export function NeonBg(props) {
  const { nodes, materials } = useGLTF(neonBgGlbUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.house_house_0.geometry} material={materials.house} position={[0.451, 3.409, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[44.56, 44.56, 3.411]} />
      <mesh geometry={nodes.lighting_lighting_0.geometry} material={materials.lighting} position={[0, 0.522, 1.152]} rotation={[-Math.PI / 2, 0, 0]} scale={[7.265, 6.913, 0.221]} />
      <mesh geometry={nodes.stage_stage5_0.geometry} material={materials.stage5} position={[0, 1.226, -0.996]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.374, 2.431, 0.105]} />
      <mesh geometry={nodes.stage_stage2_0.geometry} material={materials.stage2} position={[0, 1.226, -0.996]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.374, 2.431, 0.105]} />
      <mesh geometry={nodes.stage_stage3_0.geometry} material={materials.stage3} position={[0, 1.226, -0.996]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.374, 2.431, 0.105]} />
      <mesh geometry={nodes.stage_stage1_0.geometry} material={materials.stage1} position={[0, 1.226, -0.996]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.374, 2.431, 0.105]} />
      <mesh geometry={nodes.stage_stage4_0.geometry} material={materials.stage4} position={[0, 1.226, -0.996]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.374, 2.431, 0.105]} />
      <mesh geometry={nodes.screen_screen001_0.geometry} material={materials['screen.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.frame_frame1_0.geometry} material={materials.frame1} position={[0, 6.005, -3.012]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.76, 0.032, 4.431]} />
      <mesh geometry={nodes.frame_frame2_0.geometry} material={materials.frame2} position={[0, 6.005, -3.012]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.76, 0.032, 4.431]} />
      <mesh geometry={nodes.dec_dec1_0.geometry} material={materials.dec1} position={[-14.355, 9.466, -2.153]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.22, 5.748, 1]} />
      <mesh geometry={nodes.dec_dec2_0.geometry} material={materials.dec2} position={[-14.355, 9.466, -2.153]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.22, 5.748, 1]} />
      <mesh geometry={nodes.roof_roof2_0.geometry} material={materials.roof2} position={[0, 13.363, -0.673]} rotation={[-Math.PI / 2, 0, 0]} scale={[12.059, 11.489, 0.585]} />
      <mesh geometry={nodes.Cube_dec_cube_dec1_0.geometry} material={materials.cube_dec1} position={[-18.234, 3.551, -8.556]} rotation={[-1.231, 0.4, 0.834]} scale={[4.183, 1.135, 3.258]} />
      <mesh geometry={nodes.Cube_dec_cude_dec2_0.geometry} material={materials.cude_dec2} position={[-18.234, 3.551, -8.556]} rotation={[-1.231, 0.4, 0.834]} scale={[4.183, 1.135, 3.258]} />
      <mesh geometry={nodes.Cube_light_Cube_light2_0.geometry} material={materials.Cube_light2} position={[-17.731, 3.169, 4.589]} rotation={[Math.PI, 0.193, 0.717]} scale={[3.596, 0.976, 2.8]} />
      <mesh geometry={nodes.Cube_light_Cube_light3_0.geometry} material={materials.Cube_light3} position={[-17.731, 3.169, 4.589]} rotation={[Math.PI, 0.193, 0.717]} scale={[3.596, 0.976, 2.8]} />
      <mesh geometry={nodes.Cube_light_Cube_light4_0.geometry} material={materials.Cube_light4} position={[-17.731, 3.169, 4.589]} rotation={[Math.PI, 0.193, 0.717]} scale={[3.596, 0.976, 2.8]} />
      <mesh geometry={nodes.Cube_light_Cube_light1_0.geometry} material={materials.Cube_light1} position={[-17.731, 3.169, 4.589]} rotation={[Math.PI, 0.193, 0.717]} scale={[3.596, 0.976, 2.8]} />
      <mesh geometry={nodes.floor_floor_0.geometry} material={materials.floor} position={[0.451, 3.409, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[44.56, 44.56, 3.411]} />
    </group>
  )
}

useGLTF.preload(neonBgGlbUrl)
