import modelUrl from './planet_07.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.53KB] > F:\mongame-frontend\src\public\3d-meshes\planet_07\scene-transformed.glb [42.52KB] (-1105%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-kepler-7b-c3f70609c3e64ae4b351f6de01a74cd0
Title: Pixel Planet Kepler-7b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet07(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


