import modelUrl from './planet_08.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.54KB] > F:\mongame-frontend\src\public\3d-meshes\planet_08\scene-transformed.glb [34.07KB] (-862%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-hd-17156-b-d9a3fc5e367646aa963fbdf75dcd493e
Title: Pixel Planet HD-17156-b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet08(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


