import modelUrl from './planet_06.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.53KB] > F:\mongame-frontend\src\public\3d-meshes\planet_06\scene-transformed.glb [41.02KB] (-1062%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-kepler-16-b-016da65994f14b41a01f5e4f535d2239
Title: Pixel Planet Kepler-16 b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet06(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


