import modelUrl from './planet_01.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.54KB] > F:\mongame-frontend\src\public\3d-meshes\planet_01\scene-transformed.glb [48.91KB] (-1282%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-wise-0855-0714-8cecd383290e417d8b03c900e5d908ef
Title: Pixel Planet WISE 0855-0714
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet01(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


