import modelUrl from './planet_03.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.57KB] > F:\mongame-frontend\src\public\3d-meshes\planet_03\scene-transformed.glb [41.24KB] (-1055%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-ogle-2005-blg-390l-b-5cd60f79fd704274a68e8f76405f2d6e
Title: Pixel Planet OGLE-2005-BLG-390L b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet03(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


