import modelUrl from './planet_09.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.54KB] > F:\mongame-frontend\src\public\3d-meshes\planet_09\scene-transformed.glb [37.82KB] (-968%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-gj-15-a-c-837fdc89cf7a4895aec41181b0c1d04c
Title: Pixel Planet GJ 15 A c
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet09(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


