import modelUrl from './planet_02.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.53KB] > F:\mongame-frontend\src\public\3d-meshes\planet_02\scene-transformed.glb [45.82KB] (-1198%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-55-cancri-e-e4e4e7a6a77743b69e41d1c32ddc932e
Title: Pixel Planet 55 Cancri e
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet02(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


