import modelUrl from './planet_04.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.53KB] > F:\mongame-frontend\src\public\3d-meshes\planet_04\scene-transformed.glb [42.99KB] (-1118%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-kepler-452-b-8265e720286d4048af6f266272254730
Title: Pixel Planet Kepler-452 b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet04(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


