import modelUrl from './planet_05.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.53KB] > F:\mongame-frontend\src\public\3d-meshes\planet_05\scene-transformed.glb [40.82KB] (-1056%)
Author: AstroJar (https://sketchfab.com/AstroJar)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/pixel-planet-kepler-36-b-05a97414e94b4e3abc613af1cb9b9731
Title: Pixel Planet Kepler-36 b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Planet05(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)


