/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [111.72KB] > F:\mongame-frontend\src\public\3d-meshes\enemy_bot\scene-transformed.glb [557.05KB] (-399%)
Author: MooKorea (https://sketchfab.com/MooKorea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/patrol-bot-vgdc-cce429a5df254e19bb08cb9f26f54d6c
Title: Patrol Bot | VGDC
*/

import React, { useEffect, useMemo, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as SkeletonUtils from 'three/examples/jsm/utils/SkeletonUtils.js'
import * as THREE from 'three'
import modelUrl from './enemyBot.glb'

export function EnemyBot({ animationState = 'idle', tookDamage, ...props }) {
  const group = useRef()
  const { scene, animations } = useGLTF(modelUrl)
  
  // Clonar la escena para soportar múltiples instancias de skinned mesh sin bugs de referencias cruzadas
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  
  // Cargar las animaciones asociadas al esqueleto
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (!actions) return;
    
    // Determinar la animación correcta según el estado
    let actionName = 'Idle';

    switch (animationState?.toLowerCase()) {
      case 'attack':
        if (actions['Attack']) actionName = 'Attack';
        break;
      case 'death':
        if (actions['Death']) actionName = 'Death';
        break;
      case 'entrance':
        if (actions['Entrance']) actionName = 'Entrance';
        break;
      case 'idle':
      default:
        if (actions['Idle']) actionName = 'Idle';
        break;
    }

    const activeAction = actions[actionName];
    if (activeAction) {
      activeAction.reset();

      // Configurar bucles: las animaciones de Muerte y Entrada se reproducen una sola vez
      if (actionName === 'Death' || actionName === 'Entrance') {
        activeAction.setLoop(THREE.LoopOnce, 1);
        activeAction.clampWhenFinished = true;
      } else {
        activeAction.setLoop(THREE.LoopRepeat);
      }

      activeAction.fadeIn(0.25).play();
    }

    return () => {
      if (activeAction) {
        activeAction.fadeOut(0.25);
      }
    };
  }, [actions, animationState]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh 
          name="Object_9" 
          geometry={nodes.Object_9.geometry} 
          material={materials.Patrol} 
          skeleton={nodes.Object_9.skeleton} 
          position={[0, 4.065, -0.325]} 
          rotation={[-Math.PI / 2, 0, 0]} 
        />
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)
