/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.21KB] > F:\mongame-frontend\src\public\3d-meshes\question_mark\scene-transformed.glb [17.46KB] (-444%)
Author: UL (https://sketchfab.com/unmanned.lifemail)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/question-mark-e0969716da6c4168a1d98067be48769a
Title: question mark
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import questionMarkGlbUrl from './questionMark.glb'

export function QuestionMark(props) {
  const { nodes, materials } = useGLTF(questionMarkGlbUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Digital_blue_2} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(questionMarkGlbUrl)
