import modelUrl from './background_nebula.glb'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [3.94KB] > F:\mongame-frontend\src\public\3d-meshes\background_nebula\scene-transformed.glb [29.92KB] (-659%)
Author: Aliaksandr.melas (https://sketchfab.com/alexandr.melas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-nebula-hdri-panorama-360-skydome-5764c31489ad4504a8e49e1cde22ed3a
Title: Space nebula HDRI panorama 360 skydome
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BackgroundNebula(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['.003']} />
    </group>
  )
}

useGLTF.preload(modelUrl)

