/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [9.81KB] > F:\mongame-frontend\src\public\3d-meshes\car_garage\scene-transformed.glb [509.74KB] (-5096%)
Author: ateeq93 (https://sketchfab.com/ateeq93)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-garage-8993d2084de440eead0a1fe43f3cfa0f
Title: car garage
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import modelUrl from '@/public/3d-meshes/car_garage/scene-transformed.glb'

export function Room(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_1.geometry} material={materials.white_light} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)
