/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [13.33KB] > f:\mongame-frontend\src\public\3d-meshes\sun_02\scene-transformed.glb [636.95KB] (-4678%)
Author: Black Hole (https://sketchfab.com/blckhole)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-model-b9e1dfd765984d9b8f998bd4a6be97b5
Title: Sun Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import modelUrl from './sun_02.glb'

export function Sun(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(modelUrl)
